//
// Created by peco2282 on 2023/08/09.
//

//#ifndef UNTITLED_HELLO_JNIHELLO_H
//#define UNTITLED_HELLO_JNIHELLO_H
//
//#endif //UNTITLED_HELLO_JNIHELLO_H

/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class hello_JNIHello */

#ifndef _Included_hello_JNIHello
#define _Included_hello_JNIHello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hello_JNIHello
 * Method:    main
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hello_JNIHello_main(JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
